# Load and Inspect the Data

In [1]:
# Import the important libraries
import numpy as np 
import pandas as pd

In [2]:
# Load the dataset
df = pd.read_csv('Instagram_Analytics.csv')

In [3]:
print(df.head())

     post_id  account_id account_type  follower_count media_type  \
0  IG0000001           7        brand            3551       reel
1  IG0000002          20      creator           31095      image
2  IG0000003          15        brand            8167       reel
3  IG0000004          11      creator            9044   carousel
4  IG0000005           8      creator           15986       reel

  content_category traffic_source  has_call_to_action        post_datetime  \
0       Technology      Home Feed                   1  2024-11-30 06:00:00
1          Fitness       Hashtags                   1  2025-08-15 15:00:00
2           Beauty     Reels Feed                   0  2025-09-11 16:00:00
3            Music       External                   0  2025-09-18 03:00:00
4       Technology        Profile                   0  2025-03-21 09:00:00

    post_date  ...  comments shares  saves  reach  impressions  \
0  2024-11-30  ...         5      7     34   4327         6230
1  2025-08-15  ...        10     21     68   7451         8268
2  2025-09-11  ...         2      1     22   1639         2616
3  2025-09-18  ...         0      7      0   2877         3171
4  2025-03-21  ...         8      5     21   5350         8503

   engagement_rate  followers_gained  caption_length  hashtags_count  \
0           0.0385               899             100               7
1           0.0663               805             122               5
2           0.0531               758             115               8
3           0.0309               402             115               7
4           0.0221               155             112               9

   performance_bucket_label
0                    medium
1                     viral
2                      high
3                    medium
4                       low

[5 rows x 23 columns]

In [4]:
# the structure of your data
df.shape

(29999, 23)

In [5]:
# Columns and Data Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   post_id                   29999 non-null  object
 1   account_id                29999 non-null  int64
 2   account_type              29999 non-null  object
 3   follower_count            29999 non-null  int64
 4   media_type                29999 non-null  object
 5   content_category          29999 non-null  object
 6   traffic_source            29999 non-null  object
 7   has_call_to_action        29999 non-null  int64
 8   post_datetime             29999 non-null  object
 9   post_date                 29999 non-null  object
 10  post_hour                 29999 non-null  int64
 11  day_of_week               29999 non-null  object
 12  likes                     29999 non-null  int64
 13  comments                  29999 non-null  int64
 14  shares                    29999 non-null  int64
 15  saves                     29999 non-null  int64
 16  reach                     29999 non-null  int64
 17  impressions               29999 non-null  int64
 18  engagement_rate           29999 non-null  float64
 19  followers_gained          29999 non-null  int64
 20  caption_length            29999 non-null  int64
 21  hashtags_count            29999 non-null  int64
 22  performance_bucket_label  29999 non-null  object
dtypes: float64(1), int64(13), object(9)
memory usage: 5.3+ MB

In [6]:
# Missing Values
df.isnull().sum()

post_id                     0
account_id                  0
account_type                0
follower_count              0
media_type                  0
content_category            0
traffic_source              0
has_call_to_action          0
post_datetime               0
post_date                   0
post_hour                   0
day_of_week                 0
likes                       0
comments                    0
shares                      0
saves                       0
reach                       0
impressions                 0
engagement_rate             0
followers_gained            0
caption_length              0
hashtags_count              0
performance_bucket_label    0
dtype: int64

In [7]:
# No Missing value in dataset

In [8]:
# Mathamatical States 
df.describe()

,account_id,follower_count,has_call_to_action,post_hour,likes,comments,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count
count,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000,29999.000000
mean,10.567819,10278.305477,0.348778,11.499417,287.653588,8.521917,14.426614,42.517284,6272.475449,8466.952498,0.042107,502.152805,120.081169,7.987933
std,5.763952,6691.862669,0.476592,6.900587,317.647682,10.116505,16.420899,47.808844,4985.877059,6825.900355,0.024095,290.364038,11.009108,2.828130
min,1.000000,3083.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,268.000000,327.000000,0.000000,0.000000,70.000000,0.000000
25%,6.000000,5824.000000,0.000000,6.000000,104.000000,3.000000,5.000000,15.000000,3058.000000,4102.000000,0.024000,251.000000,113.000000,6.000000
50%,11.000000,9044.000000,0.000000,12.000000,199.000000,6.000000,10.000000,29.000000,4913.000000,6595.000000,0.040600,501.000000,120.000000,8.000000
75%,16.000000,10739.000000,1.000000,17.000000,363.000000,11.000000,19.000000,54.000000,7863.000000,10620.500000,0.057000,755.000000,127.000000,10.000000
max,20.000000,31095.000000,1.000000,23.000000,10632.000000,339.000000,516.000000,1542.000000,73339.000000,105203.000000,0.271000,1000.000000,166.000000,21.000000

# Create the Target Variable

In [9]:
# Find the median value of likes
median_likes = df['likes'].median()
print(f"The median number of likes is: {median_likes}")

The median number of likes is: 199.0

In [10]:
# Create the binary target variable
df['high_engagement'] = np.where(df['likes'] > median_likes, 1, 0)

In [11]:
print(df['high_engagement'].value_counts())

high_engagement
0    15047
1    14952
Name: count, dtype: int64

In [12]:
# Check the distribution to make sure it's balanced
print(df['high_engagement'].value_counts(normalize=True))

high_engagement
0    0.501583
1    0.498417
Name: proportion, dtype: float64

In [13]:
df.head()

,post_id,account_id,account_type,follower_count,media_type,content_category,traffic_source,has_call_to_action,post_datetime,post_date,...,shares,saves,reach,impressions,engagement_rate,followers_gained,caption_length,hashtags_count,performance_bucket_label,high_engagement
0,IG0000001,7,brand,3551,reel,Technology,Home Feed,1,2024-11-30 06:00:00,2024-11-30,...,7,34,4327,6230,0.0385,899,100,7,medium,0
1,IG0000002,20,creator,31095,image,Fitness,Hashtags,1,2025-08-15 15:00:00,2025-08-15,...,21,68,7451,8268,0.0663,805,122,5,viral,1
2,IG0000003,15,brand,8167,reel,Beauty,Reels Feed,0,2025-09-11 16:00:00,2025-09-11,...,1,22,1639,2616,0.0531,758,115,8,high,0
3,IG0000004,11,creator,9044,carousel,Music,External,0,2025-09-18 03:00:00,2025-09-18,...,7,0,2877,3171,0.0309,402,115,7,medium,0
4,IG0000005,8,creator,15986,reel,Technology,Profile,0,2025-03-21 09:00:00,2025-03-21,...,5,21,5350,8503,0.0221,155,112,9,low,0

In [14]:
print(df.columns.tolist())

['post_id', 'account_id', 'account_type', 'follower_count', 'media_type', 'content_category', 'traffic_source', 'has_call_to_action', 'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes', 'comments', 'shares', 'saves', 'reach', 'impressions', 'engagement_rate', 'followers_gained', 'caption_length', 'hashtags_count', 'performance_bucket_label', 'high_engagement']

In [15]:
df.columns

Index(['post_id', 'account_id', 'account_type', 'follower_count', 'media_type',
       'content_category', 'traffic_source', 'has_call_to_action',
       'post_datetime', 'post_date', 'post_hour', 'day_of_week', 'likes',
       'comments', 'shares', 'saves', 'reach', 'impressions',
       'engagement_rate', 'followers_gained', 'caption_length',
       'hashtags_count', 'performance_bucket_label', 'high_engagement'],
      dtype='object')